//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitters.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TwittersDBEntities : DbContext
    {
        public TwittersDBEntities()
            : base("name=TwittersDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Comments> t_Comments { get; set; }
        public virtual DbSet<t_CommentVotes> t_CommentVotes { get; set; }
        public virtual DbSet<t_Posts> t_Posts { get; set; }
        public virtual DbSet<t_PostVotes> t_PostVotes { get; set; }
        public virtual DbSet<t_Users> t_Users { get; set; }
    }
}
